### ISSUE TITLE
TVShow scrobble  'dict' object has no attribute 'to_json'

### ISSUE THREAD

**Issue by normsland** [moogar0880/PyTrakt#13]
Unfortunately it looks as though scrobble does not work as expected. I would have to thought you'd select the TVEpisode `it_crowd = TVEpisode("The IT Crowd",1,1)` then scrobble. Instead you have to select TVShow which doesn't seem to scrobble. Output below
>>> it_crowd.scrobble(85,"1.0","05-03-2015")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ffp/lib/python2.7/site-packages/trakt-2.0-py2.7.egg/trakt/tv.py", line 335, in scrobble
    return Scrobbler(self.to_json(), progress, app_version, app_date)
  File "/ffp/lib/python2.7/site-packages/trakt-2.0-py2.7.egg/trakt/sync.py", line 165, in __init__
    self.start()
  File "/ffp/lib/python2.7/site-packages/trakt-2.0-py2.7.egg/trakt/sync.py", line 169, in start
    self._post('scrobble/start')
  File "/ffp/lib/python2.7/site-packages/trakt-2.0-py2.7.egg/trakt/_core.py", line 118, in inner
    uri, data = next(generator)
  File "/ffp/lib/python2.7/site-packages/trakt-2.0-py2.7.egg/trakt/sync.py", line 202, in _post
    payload.update(self.media.to_json())
AttributeError: 'dict' object has no attribute 'to_json'

**Comment by moogar0880** [comment]
Huh, yeah, it looks like that `scrobble` method is in the wrong class. Should be a fairly simple fix, I'll get a patch up for it a little later today
