### ISSUE TITLE
Error when attempting to retrieve lists

### ISSUE THREAD

**Issue by nathan921** [moogar0880/PyTrakt#37]
I've authenticated just fine but when attempting to get a list I get an error.  I have a list named 'Shows' that includes 'Rick and Morty' and 'The Big Bang Theory'.  I've tried this on Python 2.7.10 and Python 3.5.0

```
me = users.User(MY_USER_NAME)
show_list = me.get_list('Shows')

Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    show_list = me.get_list('Shows')
  File "C:\Python27\lib\site-packages\trakt\users.py", line 398, in get_list
    return UserList.get(title, self.username)
  File "C:\Python27\lib\site-packages\trakt\core.py", line 287, in inner
    return generator.send(json_data)
  File "C:\Python27\lib\site-packages\trakt\users.py", line 102, in get
    yield UserList(creator=creator, **data)
TypeError: __new__() got an unexpected keyword argument 'created_at'
```
I also get the error when attempting to get all lists:

```
show_list = me.lists

Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    show_list = me.lists
  File "C:\Python27\lib\site-packages\trakt\core.py", line 287, in inner
    return generator.send(json_data)
  File "C:\Python27\lib\site-packages\trakt\users.py", line 244, in lists
    for ul in data]
TypeError: __new__() got an unexpected keyword argument 'created_at'
```

It looks like it's not handling all the attributes of the list(s) but I wasn't able to get to root cause.

**Comment by moogar0880** [comment]
Closed by #42
